name: Cypress Tests Poc 1

on: 
    #push

    workflow_dispatch:
    #workflow_call:
        #inputs:
            #run-name:
                #required: false
                #description: 'Test'
                #default: 'Teste completo'
                #type: string

jobs:

  #calling-workflow:
    #uses: maksonrochati/cypress-poc-2/.github/workflows/qa.yml@main
    #with:
        #config-path: cypress/e2e/teste/todo.cy.js

    
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'maksonrochati/cypress-poc-2'
          ref: 'main'
